### ISSUE TITLE
Gateway Support

### ISSUE THREAD

**Issue by michaelschmit** [minio/ming#4]
Per the minio/operator repo, there are references that this repo will be the replacement for the now deprecated helm install. There are references from 3 months ago that this repo would have a functioning helm chart in a month or so.  It appears that this repo hasn't been touched for 5 months. Are we to assume at this point that this installation option is no longer supported and will not be delivered?

**Comment by harshavardhana** [comment]
Gateway support is still as part of https://github.com/minio/minio and it ships its own helm chart currently supports NAS gateway. 

In future we may support it.  This repo is not going to get any more updates.

**Comment by michaelschmit** [comment]
Specifically I am looking for Azure gateway support. Will a helm chart targeting that deployment scenario ever be supported again?

**Comment by harshavardhana** [comment]
> Specifically I am looking for Azure gateway support. Will a helm chart targeting that deployment scenario ever be supported again?

We are not really working on it, feel free to add support for it https://github.com/minio/minio/tree/master/helm/minio 

We do not have any more cycles to support it at the moment
